import { Question } from './question';

export const QUESTIONS: Question[] = [
  { mCheck: false, lCheck: false, id: 1, displayName: 'Dễ tính, dễ đồng tình', answer: '' },
  { mCheck: false, lCheck: false, id: 2, displayName: 'Tin tưởng, đặt niềm tin vào người khác', answer: '' },
  { mCheck: false, lCheck: false, id: 3, displayName: 'Phiêu lưu, dám đương đầu với rủi ro', answer: '' },
  { mCheck: false, lCheck: false, id: 4, displayName: 'Khoan dung, đáng tôn trọng', answer: '' },
  { mCheck: false, lCheck: false, id: 5, displayName: 'Chú trọng kết quả', answer: '' },
  { mCheck: false, lCheck: false, id: 6, displayName: 'Làm phải đúng, và chính xác', answer: '' },
  { mCheck: false, lCheck: false, id: 7, displayName: 'Biến công việc trở nên thú vị', answer: '' },
  { mCheck: false, lCheck: false, id: 8, displayName: 'Cùng làm việc với nhau', answer: '' },
  { mCheck: false, lCheck: false, id: 9, displayName: 'Giáo dục, văn hoá', answer: '' },
  { mCheck: false, lCheck: false, id: 10, displayName: 'Thành tựu, giải thưởng', answer: '' },
  { mCheck: false, lCheck: false, id: 11, displayName: 'An toàn, an ninh', answer: '' },
  { mCheck: false, lCheck: false, id: 12, displayName: 'Giao lưu, họp nhóm', answer: '' },
  { mCheck: false, lCheck: false, id: 13, displayName: 'Nói nhẹ nhàng, kín đáo', answer: '' },
  { mCheck: false, lCheck: false, id: 14, displayName: 'Lạc quan, có tầm nhìn', answer: '' },
  { mCheck: false, lCheck: false, id: 15, displayName: 'Trung tâm của sự chú ý, thích giao thiệp', answer: '' },
  { mCheck: false, lCheck: false, id: 16, displayName: 'Người hoà giải, mang đến sự hoà hợp', answer: '' },
  { mCheck: false, lCheck: false, id: 17, displayName: 'Tự làm, tự chủ', answer: '' },
  { mCheck: false, lCheck: false, id: 18, displayName: 'Sẽ mua theo cảm hứng', answer: '' },
  { mCheck: false, lCheck: false, id: 19, displayName: 'Sẽ chờ đợi, không cảm thấy áp lực', answer: '' },
  { mCheck: false, lCheck: false, id: 20, displayName: 'Sẽ mua những thứ mình muốn', answer: '' },
  { mCheck: false, lCheck: false, id: 21, displayName: 'Nắm quyền, tiếp cận trực tiếp', answer: '' },
  { mCheck: false, lCheck: false, id: 22, displayName: 'Hướng ngoại, nhiệt tình', answer: '' },
  { mCheck: false, lCheck: false, id: 23, displayName: 'Dễ đoán, nhất quán', answer: '' },
  { mCheck: false, lCheck: false, id: 24, displayName: 'Cẩn trọng, cẩn thận', answer: '' },
  { mCheck: false, lCheck: false, id: 25, displayName: 'Khuyến khích người khác', answer: '' },
  { mCheck: false, lCheck: false, id: 26, displayName: 'Nỗ lực đạt đến hoàn hảo', answer: '' },
  { mCheck: false, lCheck: false, id: 27, displayName: 'Là 1 phần hòa hợp của team', answer: '' },
  { mCheck: false, lCheck: false, id: 28, displayName: 'Muốn đặt ra mục tiêu', answer: '' },
  { mCheck: false, lCheck: false, id: 29, displayName: 'Thân thiện, dễ gần', answer: '' },
  { mCheck: false, lCheck: false, id: 30, displayName: 'Cá tính, bị nhàm chán bởi sự lặp lại', answer: '' },
  { mCheck: false, lCheck: false, id: 31, displayName: 'Chủ động tạo thay đổi', answer: '' },
  { mCheck: false, lCheck: false, id: 32, displayName: 'Muốn mọi thứ một cách chính xác', answer: '' },
  { mCheck: false, lCheck: false, id: 33, displayName: 'Không dễ bị đánh bại', answer: '' },
  { mCheck: false, lCheck: false, id: 34, displayName: 'Sẽ làm những gì được yêu cầu, làm theo lãnh đạo', answer: '' },
  { mCheck: false, lCheck: false, id: 35, displayName: 'Hứng khởi, hào hứng', answer: '' },
  { mCheck: false, lCheck: false, id: 36, displayName: 'Muốn mọi thứ đúng trật tự và ngăn nắp', answer: '' },
  { mCheck: false, lCheck: false, id: 37, displayName: 'Trở nên cáu giận', answer: '' },
  { mCheck: false, lCheck: false, id: 38, displayName: 'Giữ cảm xúc bên trong', answer: '' },
  { mCheck: false, lCheck: false, id: 39, displayName: 'Kể chuyện về bản thân', answer: '' },
  { mCheck: false, lCheck: false, id: 40, displayName: 'Đứng lên phản đối', answer: '' },
  { mCheck: false, lCheck: false, id: 41, displayName: 'Không đương đầu, từ bỏ', answer: '' },
  { mCheck: false, lCheck: false, id: 42, displayName: 'Bị quá tải với chi tiết', answer: '' },
  { mCheck: false, lCheck: false, id: 43, displayName: 'Thay đổi những phút cuối', answer: '' },
  { mCheck: false, lCheck: false, id: 44, displayName: 'Đòi hỏi, cộc cằn', answer: '' },
  { mCheck: false, lCheck: false, id: 45, displayName: 'Tôi sẽ dẫn dắt họ', answer: '' },
  { mCheck: false, lCheck: false, id: 46, displayName: 'Tôi sẽ làm theo', answer: '' },
  { mCheck: false, lCheck: false, id: 47, displayName: 'Tôi sẽ thuyết phục họ', answer: '' },
  { mCheck: false, lCheck: false, id: 48, displayName: 'Tôi sẽ lấy dữ liệu', answer: '' },
  { mCheck: false, lCheck: false, id: 49, displayName: 'Sinh động, hoạt ngôn', answer: '' },
  { mCheck: false, lCheck: false, id: 50, displayName: 'Nhanh, quyết tâm', answer: '' },
  { mCheck: false, lCheck: false, id: 51, displayName: 'Cố gắng duy trì cân bằng', answer: '' },
  { mCheck: false, lCheck: false, id: 52, displayName: 'Cố gắng tuân thủ các quy tắc', answer: '' },
  { mCheck: false, lCheck: false, id: 53, displayName: 'Muốn sự cải tiến', answer: '' },
  { mCheck: false, lCheck: false, id: 54, displayName: 'Thoả mãn với mọi thứ, hài lòng', answer: '' },
  { mCheck: false, lCheck: false, id: 55, displayName: 'Cởi mở thể hiện cảm xúc', answer: '' },
  { mCheck: false, lCheck: false, id: 56, displayName: 'Khiêm tốn, giản dị', answer: '' },
  { mCheck: false, lCheck: false, id: 57, displayName: 'Nghĩ cho người khác trước', answer: '' },
  { mCheck: false, lCheck: false, id: 58, displayName: 'Ganh đua, thích thử thách', answer: '' },
  { mCheck: false, lCheck: false, id: 59, displayName: 'Lạc quan, tích cực', answer: '' },
  { mCheck: false, lCheck: false, id: 60, displayName: 'Suy nghĩ logic, hệ thống', answer: '' },
  { mCheck: false, lCheck: false, id: 61, displayName: 'Quản lý thời gian hiệu quả', answer: '' },
  { mCheck: false, lCheck: false, id: 62, displayName: 'Thường xuyên bị vội, áp lực', answer: '' },
  { mCheck: false, lCheck: false, id: 63, displayName: 'Những thứ bên ngoài quan trọng', answer: '' },
  { mCheck: false, lCheck: false, id: 64, displayName: 'Muốn kết thúc những gì đã bắt đầu', answer: '' },
  { mCheck: false, lCheck: false, id: 65, displayName: 'Bình tĩnh, kín đáo', answer: '' },
  { mCheck: false, lCheck: false, id: 66, displayName: 'Hạnh phúc, vô tư', answer: '' },
  { mCheck: false, lCheck: false, id: 67, displayName: 'Dễ chịu, tốt bụng', answer: '' },
  { mCheck: false, lCheck: false, id: 68, displayName: 'Táo bạo, dũng cảm', answer: '' },
  { mCheck: false, lCheck: false, id: 69, displayName: 'Làm hài lòng người khác, dễ chịu', answer: '' },
  { mCheck: false, lCheck: false, id: 70, displayName: 'Cười to, sôi nổi', answer: '' },
  { mCheck: false, lCheck: false, id: 71, displayName: 'Can đảm, táo bạo', answer: '' },
  { mCheck: false, lCheck: false, id: 72, displayName: 'Im lặng, kín đáo', answer: '' },
  { mCheck: false, lCheck: false, id: 73, displayName: 'Phản kháng với thay đổi đột ngột', answer: '' },
  { mCheck: false, lCheck: false, id: 74, displayName: 'Có xu hướng hứa quá nhiều', answer: '' },
  { mCheck: false, lCheck: false, id: 75, displayName: 'Bỏ cuộc khi bị áp lực', answer: '' },
  { mCheck: false, lCheck: false, id: 76, displayName: 'Không sợ đấu tranh', answer: '' },
  { mCheck: false, lCheck: false, id: 77, displayName: 'Dành thời gian chất lượng với người khác', answer: '' },
  { mCheck: false, lCheck: false, id: 78, displayName: 'Lên kế hoạch tương lai, luôn sẵn sàng', answer: '' },
  { mCheck: false, lCheck: false, id: 79, displayName: 'Bắt đầu cuộc phiêu lưu mới', answer: '' },
  { mCheck: false, lCheck: false, id: 80, displayName: 'Nhận thưởng cho các mục tiêu đã hoàn thành', answer: '' },
  { mCheck: false, lCheck: false, id: 81, displayName: 'Muốn nhiều quyền hơn', answer: '' },
  { mCheck: false, lCheck: false, id: 82, displayName: 'Muốn cơ hội mới', answer: '' },
  { mCheck: false, lCheck: false, id: 83, displayName: 'Tránh mọi xung đột', answer: '' },
  { mCheck: false, lCheck: false, id: 84, displayName: 'Muốn định hướng rõ ràng', answer: '' },
  { mCheck: false, lCheck: false, id: 85, displayName: 'Một người động viên tốt', answer: '' },
  { mCheck: false, lCheck: false, id: 86, displayName: 'Một người lắng nghe tốt', answer: '' },
  { mCheck: false, lCheck: false, id: 87, displayName: 'Một người phân tích tốt', answer: '' },
  { mCheck: false, lCheck: false, id: 88, displayName: 'Một người điều phối tốt', answer: '' },
  { mCheck: false, lCheck: false, id: 89, displayName: 'Thách thức các nguyên tắc, quy định', answer: '' },
  { mCheck: false, lCheck: false, id: 90, displayName: 'Luật lệ phải tạo ra công bằng', answer: '' },
  { mCheck: false, lCheck: false, id: 91, displayName: 'Luật lệ khiến mọi thứ nhàm chán', answer: '' },
  { mCheck: false, lCheck: false, id: 92, displayName: 'Luật lệ khiến mọi thứ an toàn', answer: '' },
  { mCheck: false, lCheck: false, id: 93, displayName: 'Đáng tin cậy', answer: '' },
  { mCheck: false, lCheck: false, id: 94, displayName: 'Sáng tạo, độc đáo', answer: '' },
  { mCheck: false, lCheck: false, id: 95, displayName: 'Kết quả, định hướng kết quả', answer: '' },
  { mCheck: false, lCheck: false, id: 96, displayName: 'Có tiêu chuẩn cao, chính xác', answer: '' }
];





